In [ ]:
 #  Data Talks Club - Machine Learning Zoomcamp
 #  Session 1

Set up the environment
You need to install Python, NumPy, Pandas, Matplotlib and Seaborn.

In [231]:
import numpy as np
import pandas as pd
 #  import matplotlib as mpl
 #  import seaborn as sns

In [ ]:
 # Q1. Pandas version
 # What's the version of Pandas that you installed?
 # 
 #  You can get the version information using the __version__ field:

In [3]:
import platform
print(platform.python_version())

3.12.4


In [ ]:
 # Getting the data
 # For this homework, we'll use the Laptops Price dataset. Download it from here.
 # 
 # You can do it with wget # : # 

 # 
wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops # .c # sv # 
Or just open it with  your browser and click "Save as. # . # ". #  

Now read it with  ou ouPandas.

In [11]:
df = pd.read_csv('C:/Users/arcangelaac/Downloads/laptops.csv')

In [3]:
 #  Q2. Records count
 #  How many records are in the dataset?
 #   12 # 
 # 000
 # 21 # 60 # 
12160

12160

In [13]:
df.shape

(2160, 12)

In [15]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [31]:
df.index

RangeIndex(start=0, stop=2160, step=1)

In [ ]:
# Q3. Laptop brands
# How many laptop brands are presented in the dataset?
# 
# 12
 

7 
22# # 8
2160

In [37]:
df_group_brand = df.groupby('Brand')

In [45]:
df_group_brand.describe()

RAM                                                       \
                  count       mean        std   min   25%   50%   75%    max   
Brand                                                                          
Acer              137.0  12.204380   6.218023   4.0   8.0   8.0  16.0   32.0   
Alurin             29.0   9.655172   3.298007   8.0   8.0   8.0   8.0   16.0   
Apple             116.0  13.034483   7.480910   4.0   8.0   8.0  16.0   32.0   
Asus              415.0  16.404819   9.757939   4.0   8.0  16.0  16.0   64.0   
Deep Gaming         8.0  44.000000  16.561573  32.0  32.0  32.0  64.0   64.0   
Dell               84.0  11.380952   4.583640   4.0   8.0   8.0  16.0   32.0   
Denver              1.0   4.000000        NaN   4.0   4.0   4.0   4.0    4.0   
Dynabook Toshiba   19.0  10.526316   3.820535   8.0   8.0   8.0  16.0   16.0   
Gigabyte           48.0  17.500000   5.128145   8.0  16.0  16.0  16.0   32.0   
HP                368.0  11.967391   6.336523   4.0   8.0   8.0  16.0   32.0   
Innjoo              6.0   6.333333   1.505545   4.0   6.0   6.0   7.5    8.0   
Jetwing             1.0   8.000000        NaN   8.0   8.0   8.0   8.0    8.0   
LG                 32.0  21.750000   8.911754   8.0  16.0  16.0  32.0   32.0   
Lenovo            366.0  12.382514   5.800909   4.0   8.0   8.0  16.0   32.0   
MSI               308.0  25.168831  13.776629   8.0  16.0  16.0  32.0  128.0   
Medion             32.0  10.875000   7.753251   4.0   8.0   8.0  10.0   32.0   
Microsoft          77.0  12.103896   5.655888   4.0   8.0   8.0  16.0   32.0   
Millenium           2.0  16.000000   0.000000  16.0  16.0  16.0  16.0   16.0   
PcCom              24.0  20.666667   7.428890  16.0  16.0  16.0  32.0   32.0   
Primux              8.0   7.000000   1.851640   4.0   7.0   8.0   8.0    8.0   
Prixton             3.0   4.000000   0.000000   4.0   4.0   4.0   4.0    4.0   
Razer              37.0  21.621622   7.743640  16.0  16.0  16.0  32.0   32.0   
Realme              1.0   8.000000        NaN   8.0   8.0   8.0   8.0    8.0   
Samsung            22.0  14.000000   6.141196   4.0  10.0  16.0  16.0   32.0   
Thomson             4.0   6.000000   2.309401   4.0   4.0   6.0   8.0    8.0   
Toshiba             1.0   8.000000        NaN   8.0   8.0   8.0   8.0    8.0   
Vant               11.0  19.636364  10.346717   8.0  16.0  16.0  16.0   40.0   

                 Storage               ...  Screen       Final Price  \
                   count         mean  ...     75%   max       count   
Brand                                  ...                             
Acer               137.0   536.291971  ...  15.600  17.3       137.0   
Alurin              29.0   352.551724  ...  15.600  15.6        29.0   
Apple              116.0   508.620690  ...  15.075  16.2       116.0   
Asus               415.0   634.775904  ...  15.600  18.0       415.0   
Deep Gaming          8.0  1250.000000  ...  17.300  17.3         8.0   
Dell                84.0   395.142857  ...  15.600  17.0        84.0   
Denver               1.0   256.000000  ...  14.000  14.0         1.0   
Dynabook Toshiba    19.0   404.210526  ...  15.600  15.6        19.0   
Gigabyte            48.0   860.166667  ...  16.000  17.3        48.0   
HP                 368.0   479.260870  ...  15.600  17.3       368.0   
Innjoo               6.0   192.000000  ...  15.225  15.6         6.0   
Jetwing              1.0   256.000000  ...  15.600  15.6         1.0   
LG                  32.0   703.000000  ...  17.000  17.0        32.0   
Lenovo             366.0   471.475410  ...  15.600  17.3       366.0   
MSI                308.0   956.441558  ...  17.000  17.3       308.0   
Medion              32.0   494.000000  ...  15.600  17.3        32.0   
Microsoft           77.0   394.285714  ...  14.400  15.0        77.0   
Millenium            2.0   500.000000  ...  15.600  15.6         2.0   
PcCom               24.0   688.000000  ...  15.600  17.3        24.0   
Primux               8.0   288.0000

In [49]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

In [ ]:
# Q4. Missing values
# How many columns in the dataset have missing values?

# 0
# 1
# 2
# 3

In [51]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [ ]:
# Q5. Maximum final price
# 
#  What's the maximum final price of Dell notebooks in the dataset?
# 
8#8 69
33# 691
# 389

#  I see the solution in a previous step (3936), but I want to ask directly to get the value
3936

In [77]:
df = df.rename(columns={'Final Price' : 'Final_Price'})

In [81]:
df.groupby('Brand').Final_Price.max().loc['Dell']

3936.0

In [119]:
df[df['Brand']=='Dell']['Final_Price'].max()

3936.0

In [ ]:
# Q6. Median value of Screen
# 
# Find the median value of Screen column in the dataset.# 
# 
Next, calculate the most frequent value of the same Screen column# .# 
Use fillna method to fill the missing values in Screen column with the most frequent value from the previous ste# p# .
Now, calculate the median value of Screen once aga# i# n.
Has it chang# e# d?

Hint: refer to existing mode and median functions to complete the # tas# k# .# 

Yes
No

In [ ]:
# Find the median value of Screen column in the dataset.

In [89]:
df2 = df['Screen'].median()
print(' The median of "Screen" column is :', df2)

 The median of "Screen" column is : 15.6


In [ ]:
# Next, calculate the most frequent value of the same Screen column.

In [113]:
df3 = df['Screen'].mode()
print(' The mode of "Screen" column is :', df3)

 The mode of "Screen" column is : Series([], Name: Screen, dtype: object)


In [ ]:
# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

In [107]:
df["Screen"] = df["Screen"].fillna(df['Screen'].mode())

In [117]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen          2160
Touch              0
Final_Price        0
dtype: int64

In [ ]:
  # I made one error, I will read again the source using the suuggestion in FAQ

In [121]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"
df_new = pd.read_csv(url)

In [181]:
df_new['Screen'].isnull().sum()

4

In [131]:
df3

Series([], Name: Screen, dtype: object)

In [139]:
df_new.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [145]:
df_new.Screen.nunique()

29

In [147]:
df_new.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [155]:
df_new.groupby(['Screen']).count()

Laptop  Status  Brand  Model   CPU   RAM  Storage  Storage type  GPU  \
Screen                                                                         
10.10        1       1      1      1     1     1        1             1    0   
10.50        7       7      7      7     7     7        7             7    0   
10.95        1       1      1      1     1     1        1             1    0   
11.60       16      16     16     16    16    16       16            12    0   
12.00        4       4      4      4     4     4        4             0    0   
12.30       13      13     13     13    13    13       13            10    0   
12.40        6       6      6      6     6     6        6             5    0   
12.50        1       1      1      1     1     1        1             1    0   
13.00       27      27     27     27    27    27       27            23    0   
13.30      131     131    131    131   131   131      131           126    0   
13.40       19      19     19     19    19    19       19            19    8   
13.50       19      19     19     19    19    19       19            19    0   
13.60       11      11     11     11    11    11       11            11    0   
13.90        2       2      2      2     2     2        2             2    0   
14.00      392     392    392    392   392   392      392           386   48   
14.10       11      11     11     11    11    11       11            11    0   
14.20       14      14     14     14    14    14       14            14    0   
14.40        6       6      6      6     6     6        6             6    4   
14.50        3       3      3      3     3     3        3             3    0   
15.00       21      21     21     21    21    21       21            20    0   
15.30        8       8      8      8     8     8        8             8    0   
15.40        5       5      5      5     5     5        5             5    3   
15.60     1009    1009   1009   1009  1009  1009     1009           997  370   
16.00      174     174    174    174   174   174      174           173  135   
16.10       48      48     48     48    48    48       48            47   47   
16.20       10      10     10     10    10    10       10            10    0   
17.00       33      33     33     33    33    33       33            33   24   
17.30      161     161    161    161   161   161      161           161  144   
18.00        3       3      3      3     3     3        3             3    3   

        Touch  Final Price  
Screen                      
10.10       1            1  
10.50       7            7  
10.95       1            1  
11.60      16           16  
12.00       4            4  
12.30      13           13  
12.40       6            6  
12.50       1            1  
13.00      27           27  
13.30     131          131  
13.40      19           19  
13.50      19           19  
13.60      11           11  
13.90       2            2  
14.00     392          392  
14.10      11           11  
14.20      14           14  
14.40       6            6  
14.50       3            3  
15.00      21           21  
15.30       8            8  
15.40       5            5  
15.60    1009         1009  
16.00     174          174  
16.10      48           48  
16.20      10           10  
17.00      33           33  
17.30     161          161  
18.00       3            3

In [161]:
df_new[df_new['Screen']==' ']

Empty DataFrame
Columns: [Laptop, Status, Brand, Model, CPU, RAM, Storage, Storage type, GPU, Screen, Touch, Final Price]
Index: []

In [ ]:
 # Using FAQ suggestion about MODE

In [173]:
mode = df_new['Screen'].mode()

In [175]:
single_valor_mode = mode[0]

In [177]:
single_valor_mode       

15.6

In [ ]:
 # FILLNA

In [185]:
df_new["Screen"] = df_new["Screen"].fillna(single_valor_mode)

In [187]:
df_new['Screen'].isnull().sum()

0

In [189]:
df_new["Screen"] 

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [191]:
df_new['Screen'].median()

15.6

In [ ]:
 # Q7. Sum of weights
 # 1. Select all the "Innjoo" laptops from the dataset. # 2. 
 # 2. 
Select only columns RAM, Storage, Screen # 3. . # 3. 
Get the underlying  N umPy array. Let's call it  # 4. X # 4. .
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result X # 5. T # 5. X.
Compute the inverse 6. X # 6. TX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1 # 7. 1 # 7. 00].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the res # 8. u # 8. lt w.
What's the sum of all the elements of the  # r # esult?
Note: You just implemented linear regression. We'll talk about it in the next  # lesso # n.

 # 0.43 # 
 # 4 # 5.29
0
45.58
91.30

In [ ]:
 # 1. Select all the "Innjoo" laptops from the dataset.

In [201]:
df_Injoo = df_new[df_new['Brand']=='Innjoo']

In [203]:
df_Injoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [ ]:
# 2. Select only columns RAM, Storage, Screen.

In [215]:
df_q7 = df_Injoo.loc[ : ,[ 'RAM', 'Storage','Screen'] ]

In [217]:
df_q7

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [ ]:
# 3. Get the underlying NumPy array. Let's call it X.

In [219]:
X = df_q7.values

In [221]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [ ]:
# 4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [223]:
XT = X.transpose()

In [225]:
XT

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [235]:
XTX = XT.dot(X)

In [237]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [ ]:
# 5. Compute the inverse of XTX.

In [239]:
XTX_inv = np.linalg.inv(XTX)

In [241]:
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [ ]:
 # 6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

In [243]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [245]:
y

array([1100, 1300,  800,  900, 1000, 1100])

In [ ]:
 # 7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [247]:
  w = XTX_inv.dot(XT) 

In [249]:
    w

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [251]:
   w = w.dot(y)

In [253]:
w

array([45.58076606,  0.42783519, 45.29127938])

In [ ]:
 # 8. What's the sum of all the elements of the result?

In [257]:
sum_w = w.sum()

In [259]:
sum_w

91.29988062995815

In [ ]:
 # END